In [211]:
def solution(a):
    a.sort(key = lambda x: x[1])
    start = 'ICN'

    a_dict = {}
    for i in a:
        a_dict[i[0]] = a_dict.get(i[0], [])
        a_dict[i[0]].append(i[1])
    for i in a:
        a_dict[i[1]]= a_dict.get(i[1], [])
        a_dict[i[1]].append(i[0])
    
    count = []
    
    def dfs(a_dict, a, start):
        count.append(start)
        for i in a_dict[start]:
            if [start, i] in a:
                a.remove([start, i])
                a_dict[i].remove(start)
                dfs(a_dict, a, i)
    dfs(a_dict, a, start)
    return count

In [10]:
def solution(a):
    a.sort(key = lambda x: x[1])
    start = 'ICN'

    a_dict = {}
    for i in a:
        a_dict[i[0]] = a_dict.get(i[0], [])
        a_dict[i[0]].append(i[1])
        a_dict[i[1]]= a_dict.get(i[1], [])
        a_dict[i[1]].append(i[0])
        
    count = []

    def dfs(a_dict, a, start):
        count.append(start)
        for i in a_dict[start]:
            if [start, i] in a:
                a.remove([start, i])
                a_dict[i].remove(start)
                dfs(a_dict, a, i)
    dfs(a_dict, a, start)
    return count

In [12]:
print(solution([["ICN", "BOO"], ["ICN", "COO"], 
                ["COO", "DOO"], ["DOO", "COO"], 
                ["BOO", "DOO"], ["DOO", "BOO"], 
                ["BOO", "ICN"], ["COO", "BOO"]]))

['ICN', 'BOO', 'DOO', 'COO', 'BOO', 'ICN', 'COO', 'DOO', 'BOO']


In [11]:
#print(solution([["ICN", "SFO"], ["ICN", "ATL"], ["SFO", "ATL"], ["ATL", "ICN"], ["ATL","SFO"]]))
#print(solution([["ICN", "JFK"], ["HND", "IAD"], ["JFK", "HND"]]))
#print(solution([["ICN", "SFO"], ["ICN", "ATL"], ["SFO", "ATL"], ["ATL", "ICN"], ["ATL","SFO"],['ICN','ICN']]))
#print(solution([["ICN", "AOO"], ["AOO", "BOO"], ["BOO", "COO"], 
#                ["COO", "DOO"], ["DOO", "EOO"], ["EOO", "DOO"], 
#                ["DOO", "COO"], ["COO", "BOO"], ["BOO", "AOO"]]))
#print(solution([["ICN", "B"], ["B", "ICN"], ["ICN", "A"], ["A", "D"], ["D", "A"]]))
#print(solution([["ICN", "AAA"], ["ICN", "AAA"], ["ICN", "AAA"], ["AAA", "ICN"], ["AAA", "ICN"]]))
#print(solution([["ICN", "COO"], ["ICN", "BOO"], ["COO", "ICN"], ["BOO", "DOO"]]))


In [243]:
a

[]

In [1]:
a = [["ICN", "BOO"], ["ICN", "COO"], 
     ["COO", "DOO"], ["DOO", "COO"], 
     ["BOO", "DOO"], ["DOO", "BOO"], 
     ["BOO", "ICN"], ["COO", "BOO"]]
a.sort(key = lambda x: x[1])
start = 'ICN'

a_dict = {}
for i in a:
    a_dict[i[0]] = a_dict.get(i[0], [])
    a_dict[i[0]].append(i[1])
    a_dict[i[1]]= a_dict.get(i[1], [])
    a_dict[i[1]].append(i[0])

count = []


stack =[]

def dfs(a_dict, a, start):
    count.append(start)
    print(start, end = ' ')
    for i in a_dict[start]:
        if [start, i] in a:
            a.remove([start, i])
            a_dict[i].remove(start)
            dfs(a_dict, a, i)
dfs(a_dict, a, start)


ICN BOO DOO COO BOO ICN COO DOO BOO 

In [2]:
a = [["ICN", "BOO"], ["ICN", "COO"], 
     ["COO", "DOO"], ["DOO", "COO"], 
     ["BOO", "DOO"], ["DOO", "BOO"], 
     ["BOO", "ICN"], ["COO", "BOO"]]

a_dict={}
for i in a:
    a_dict[i[0]] = a_dict.get(i[0], [])
    a_dict[i[0]].append(i[1])
a_dict

{'ICN': ['BOO', 'COO'],
 'COO': ['DOO', 'BOO'],
 'DOO': ['COO', 'BOO'],
 'BOO': ['DOO', 'ICN']}

In [7]:
visited = {}
for i in a:
    visited[i[0]] = visited.get(i[0], 0)

visited

{'ICN': 0, 'COO': 0, 'DOO': 0, 'BOO': 0}

In [64]:
#a = [["ICN", "BOO"], ["ICN", "COO"], 
#     ["COO", "DOO"], ["DOO", "COO"], 
#     ["BOO", "DOO"], ["DOO", "BOO"], 
#     ["BOO", "ICN"], ["COO", "BOO"]]
a = [["ICN", "SFO"], ["ICN", "ATL"], ["SFO", "ATL"], ["ATL", "ICN"], ["ATL","SFO"]]
a.sort(key = lambda x: x[1])
start = 'ICN'

a_dict = {}
for i in a:
    a_dict[i[0]] = a_dict.get(i[0], [])
    a_dict[i[0]].append(i[1])
    a_dict[i[1]]= a_dict.get(i[1], [])
    a_dict[i[1]].append(i[0])
    
visited = {}
for i in a:
    visited[(i[0]+i[1])] = visited.get((i[0]+i[1]), False)

count = []
def dfs(a_dict, a, start):
    count.append(start)
    print('start:', start, end = ' ')
    for i in a_dict[start]:
        if (start+i) in visited and not visited[(start+i)]:
            print('start: ', start, 'i: ', i)
            
            visited[(start+i)] = True
            a_dict[i].remove(start)
            dfs(a_dict, a, i)
dfs(a_dict, a, start)
#  ["ICN", "BOO", "DOO", "BOO", "ICN", "COO", "DOO", "COO", "BOO"]

start: ICN start:  ICN i:  ATL
start: ATL start:  ATL i:  SFO
start: SFO start:  SFO i:  ATL
start: ATL start:  ATL i:  ICN
start: ICN start:  ICN i:  SFO
start: SFO 

In [49]:
visited

{'ICNBOO': True,
 'DOOBOO': True,
 'COOBOO': True,
 'ICNCOO': True,
 'DOOCOO': False,
 'COODOO': False,
 'BOODOO': True,
 'BOOICN': True}

In [65]:
a = [["ICN", "SFO"], ["ICN", "ATL"], ["SFO", "ATL"], ["ATL", "ICN"], ["ATL","SFO"]]
#a = [["ICN", "BOO"], ["ICN", "COO"], 
#     ["COO", "DOO"], ["DOO", "COO"], 
#     ["BOO", "DOO"], ["DOO", "BOO"], 
#     ["BOO", "ICN"], ["COO", "BOO"]]
a.sort(key = lambda x: x[1])
start = 'ICN'

a_dict = {}
for i in a:
    a_dict[i[0]] = a_dict.get(i[0], [])
    a_dict[i[0]].append(i[1])
    a_dict[i[1]]= a_dict.get(i[1], [])
    a_dict[i[1]].append(i[0])

count = []

stack =[]
print(a_dict)
def dfs(a_dict, a, start):
    count.append(start)
    #print(start, end = ' ')
    for i in a_dict[start]:
        if [start, i] in a:
            a.remove([start, i])
            a_dict[i].remove(start)
            dfs(a_dict, a, i)
dfs(a_dict, a, start)
#["ICN", "BOO", "DOO", "BOO", "ICN", "COO", "DOO", "COO", "BOO"]

{'ICN': ['ATL', 'ATL', 'SFO'], 'ATL': ['ICN', 'SFO', 'ICN', 'SFO'], 'SFO': ['ATL', 'ICN', 'ATL']}
---------------------
['ICN', 'SFO', 'ICN', 'SFO']
['SFO', 'ICN', 'SFO']
____________________
---------------------
['ATL', 'ATL', 'SFO']
['ATL', 'SFO']
____________________
---------------------
['ATL', 'ICN', 'ATL']
['ATL', 'ATL']
____________________
---------------------
['SFO', 'ICN', 'SFO']
['ICN', 'SFO']
____________________
---------------------
['ATL', 'ATL']
['ATL']
____________________


In [238]:
import copy
#a = [["ICN", "SFO"], ["ICN", "ATL"], ["SFO", "ATL"], ["ATL", "ICN"], ["ATL","SFO"]]
a = [["ICN", "BOO"], ["ICN", "COO"], 
     ["COO", "DOO"], ["DOO", "COO"], 
     ["BOO", "DOO"], ["DOO", "BOO"], 
     ["BOO", "ICN"], ["COO", "BOO"]]
a.sort(key = lambda x: x[1])
length_a = len(a)
start = 'ICN'

a_dict = {}
for i in a:
    a_dict[i[0]] = a_dict.get(i[0], [])
    a_dict[i[0]].append(i[1])
    a_dict[i[1]]= a_dict.get(i[1], [])
    a_dict[i[1]].append(i[0])

count = []
stack = []
def dfs(a_dict, a, start, stack):
    if len(stack) < length_a+1:

        for i in a_dict[start]:
            if [start, i] in a:
                ab = copy.deepcopy(a)
                ab.remove([start, i])
                dfs(a_dict, ab, i, stack+[i])
    else:
        if stack not in count:
            count.append(stack)

dfs(a_dict, a, 'ICN', ['ICN'])        
count.sort()
print(count)
#["ICN", "BOO", "DOO", "BOO", "ICN", "COO", "DOO", "COO", "BOO"]

[['ICN', 'BOO', 'DOO', 'BOO', 'ICN', 'COO', 'DOO', 'COO', 'BOO'], ['ICN', 'BOO', 'DOO', 'COO', 'BOO', 'ICN', 'COO', 'DOO', 'BOO'], ['ICN', 'BOO', 'DOO', 'COO', 'DOO', 'BOO', 'ICN', 'COO', 'BOO'], ['ICN', 'BOO', 'ICN', 'COO', 'BOO', 'DOO', 'COO', 'DOO', 'BOO'], ['ICN', 'BOO', 'ICN', 'COO', 'DOO', 'BOO', 'DOO', 'COO', 'BOO'], ['ICN', 'BOO', 'ICN', 'COO', 'DOO', 'COO', 'BOO', 'DOO', 'BOO'], ['ICN', 'COO', 'BOO', 'DOO', 'COO', 'DOO', 'BOO', 'ICN', 'BOO'], ['ICN', 'COO', 'BOO', 'ICN', 'BOO', 'DOO', 'COO', 'DOO', 'BOO'], ['ICN', 'COO', 'DOO', 'BOO', 'DOO', 'COO', 'BOO', 'ICN', 'BOO'], ['ICN', 'COO', 'DOO', 'BOO', 'ICN', 'BOO', 'DOO', 'COO', 'BOO'], ['ICN', 'COO', 'DOO', 'COO', 'BOO', 'DOO', 'BOO', 'ICN', 'BOO'], ['ICN', 'COO', 'DOO', 'COO', 'BOO', 'ICN', 'BOO', 'DOO', 'BOO']]


In [7]:
import copy
#a = [["ICN", "SFO"], ["ICN", "ATL"], ["SFO", "ATL"], ["ATL", "ICN"], ["ATL","SFO"]]
a = [["ICN", "BOO"], ["ICN", "COO"], 
     ["COO", "DOO"], ["DOO", "COO"], 
     ["BOO", "DOO"], ["DOO", "BOO"], 
     ["BOO", "ICN"], ["COO", "BOO"]]
a.sort(key = lambda x: x[1])
length_a = len(a)
start = 'ICN'

a_dict = {}
for i in a:
    a_dict[i[0]] = a_dict.get(i[0], [])
    a_dict[i[0]].append(i[1])
    a_dict[i[1]]= a_dict.get(i[1], [])
    a_dict[i[1]].append(i[0])

visited = {}
for i in a:
    visited[(i[0], i[1])] = visited.get((i[0], i[1]), False)

count = []
stack = []
def dfs(a_dict, a, start, stack, visited):
    
    if len(stack) < length_a+1:
        for i in a_dict[start]:
            if [start, i] in a and not visited[(start, i)]:
                visited_i = copy.deepcopy(visited)
                visited_i[(start, i)] = True
                if stack in count:
                    return
                else:
                    dfs(a_dict, a, i, stack+[i], visited_i)
    else:
        if stack not in count:
             

dfs(a_dict, a, 'ICN', ['ICN'], visited)        
count.sort()
print(count)
#["ICN", "BOO", "DOO", "BOO", "ICN", "COO", "DOO", "COO", "BOO"]

[['ICN', 'BOO', 'DOO', 'BOO', 'ICN', 'COO', 'DOO', 'COO', 'BOO'], ['ICN', 'BOO', 'DOO', 'COO', 'BOO', 'ICN', 'COO', 'DOO', 'BOO'], ['ICN', 'BOO', 'DOO', 'COO', 'DOO', 'BOO', 'ICN', 'COO', 'BOO'], ['ICN', 'BOO', 'ICN', 'COO', 'BOO', 'DOO', 'COO', 'DOO', 'BOO'], ['ICN', 'BOO', 'ICN', 'COO', 'DOO', 'BOO', 'DOO', 'COO', 'BOO'], ['ICN', 'BOO', 'ICN', 'COO', 'DOO', 'COO', 'BOO', 'DOO', 'BOO'], ['ICN', 'COO', 'BOO', 'DOO', 'COO', 'DOO', 'BOO', 'ICN', 'BOO'], ['ICN', 'COO', 'BOO', 'ICN', 'BOO', 'DOO', 'COO', 'DOO', 'BOO'], ['ICN', 'COO', 'DOO', 'BOO', 'DOO', 'COO', 'BOO', 'ICN', 'BOO'], ['ICN', 'COO', 'DOO', 'BOO', 'ICN', 'BOO', 'DOO', 'COO', 'BOO'], ['ICN', 'COO', 'DOO', 'COO', 'BOO', 'DOO', 'BOO', 'ICN', 'BOO'], ['ICN', 'COO', 'DOO', 'COO', 'BOO', 'ICN', 'BOO', 'DOO', 'BOO']]


In [8]:
count

[['ICN', 'BOO', 'DOO', 'BOO', 'ICN', 'COO', 'DOO', 'COO', 'BOO'],
 ['ICN', 'BOO', 'DOO', 'COO', 'BOO', 'ICN', 'COO', 'DOO', 'BOO'],
 ['ICN', 'BOO', 'DOO', 'COO', 'DOO', 'BOO', 'ICN', 'COO', 'BOO'],
 ['ICN', 'BOO', 'ICN', 'COO', 'BOO', 'DOO', 'COO', 'DOO', 'BOO'],
 ['ICN', 'BOO', 'ICN', 'COO', 'DOO', 'BOO', 'DOO', 'COO', 'BOO'],
 ['ICN', 'BOO', 'ICN', 'COO', 'DOO', 'COO', 'BOO', 'DOO', 'BOO'],
 ['ICN', 'COO', 'BOO', 'DOO', 'COO', 'DOO', 'BOO', 'ICN', 'BOO'],
 ['ICN', 'COO', 'BOO', 'ICN', 'BOO', 'DOO', 'COO', 'DOO', 'BOO'],
 ['ICN', 'COO', 'DOO', 'BOO', 'DOO', 'COO', 'BOO', 'ICN', 'BOO'],
 ['ICN', 'COO', 'DOO', 'BOO', 'ICN', 'BOO', 'DOO', 'COO', 'BOO'],
 ['ICN', 'COO', 'DOO', 'COO', 'BOO', 'DOO', 'BOO', 'ICN', 'BOO'],
 ['ICN', 'COO', 'DOO', 'COO', 'BOO', 'ICN', 'BOO', 'DOO', 'BOO']]

In [71]:
count.count(max(count))

3

In [179]:

vector = [[+1, 0], [+1, +1], [0, +1], [-1, +1], [-1, 0], [-1, -1], [0, -1], [+1, -1]]

arrows = list(reversed([6, 6, 6, 4, 4, 4, 2, 2, 2, 0, 0, 0, 1, 6, 5, 5, 3, 6, 0]))
a = deque([deque([1])])
x = 0
y = 0
count = 0
while arrows:
    coordi = arrows.pop()
    x += vector[coordi][0]
    y += vector[coordi][1]
    if x < 0:
        a.appendleft(deque([0] * len(a[0])))
        x += 1
    if x >=len(a):
        a.append(deque([0] * len(a[0])))
    
    if y < 0:
        for i in range(len(a)):
            a[i].appendleft(0)
        y += 1
        
    if y >= len(a[0]):
        for i in range(len(a)):
            a[i].append(0)
    a[x][y] +=1
    if a[x][y] >= 2:
        count += 1

In [180]:
count

3

In [173]:
print(x, y)

4 4


In [178]:
import numpy as np
np.array(a)

array([[1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [1, 2, 0, 1, 0],
       [1, 1, 2, 2, 0],
       [0, 0, 0, 1, 1]])

In [211]:

vector = [[+1, 0], [+1, +1], [0, +1], [-1, +1], [-1, 0], [-1, -1], [0, -1], [+1, -1]]

arrows = list(reversed([6, 6, 6, 4, 4, 4, 2, 2, 2, 0, 0, 0, 1, 6, 5, 5, 3, 6, 0]))
count = 0
while arrows:
    print(arrows)
    a = deque([deque([1])])
    x = 0
    y = 0
    while arrows:
        coordi = arrows.pop()
        x += vector[coordi][0]
        y += vector[coordi][1]
        boolian = False
        if x < 0:
            a.appendleft(deque([0] * len(a[0])))
            x += 1
            boolian = True
        if x >=len(a):
            a.append(deque([0] * len(a[0])))
            boolian = True
        if y < 0:
            for i in range(len(a)):
                a[i].appendleft(0)
            y += 1
            boolian = True
        if y >= len(a[0]):
            for i in range(len(a)):
                a[i].append(0)
            boolian = True
        if boolian:
            print(np.array(a))
        a[x][y] +=1
        if a[x][y] >= 2:
            break
    print(np.array(a))

[0, 6, 3, 5, 5, 6, 1, 0, 0, 0, 2, 2, 2, 4, 4, 4, 6, 6, 6]
[[0 1]]
[[0 1 1]]
[[0 1 1 1]]
[[0 0 0 0]
 [1 1 1 1]]
[[0 0 0 0]
 [1 0 0 0]
 [1 1 1 1]]
[[0 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 1 1]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 2]]
[0, 6, 3, 5, 5, 6, 1]
[[1 0]
 [0 0]]
[[0 1 0]
 [0 1 1]]
[[0 0 0 0]
 [0 1 1 0]
 [0 0 1 1]]
[[0 0 0 0]
 [1 0 0 0]
 [0 1 1 0]
 [0 0 1 1]]
[[1 1 0 0]
 [2 0 0 0]
 [0 1 1 0]
 [0 0 1 1]]


In [88]:
from collections import deque
import copy
vector = [[+1, 0], [+1, +1], [0, +1], [-1, +1], [-1, 0], [-1, -1], [0, -1], [+1, -1]]

arrows = list(reversed([6, 6, 6, 4, 4, 4, 2, 2, 2, 0, 0, 0, 1, 6, 5, 5, 3, 6, 0]))
a = deque([deque([1])])
x = 0
y = 0
count = 0

while arrows:
    coordi = arrows.pop() 
    x += vector[coordi][0]
    y += vector[coordi][1]
    
    if x < 0:
        a.appendleft(deque([0] * len(a[0])))
        x += 1
        boolian = True
    if x >=len(a):
        a.append(deque([0] * len(a[0])))
        boolian = True
    if y < 0:
        for i in range(len(a)):
            a[i].appendleft(0)
        y += 1 
        boolian = True
    if y >= len(a[0]):
        for i in range(len(a)):
            a[i].append(0)
        boolian = True
    
    a[x][y] +=1

        

In [89]:
a

deque([deque([1, 1, 1, 1, 0]),
       deque([1, 1, 1, 1, 0]),
       deque([1, 2, 0, 1, 0]),
       deque([1, 1, 2, 2, 0]),
       deque([0, 0, 0, 1, 1])])

In [112]:
from collections import deque
import numpy as np
import copy
vector = [[+1, 0], [+1, +1], [0, +1], [-1, +1], [-1, 0], [-1, -1], [0, -1], [+1, -1]]

arrows = list(reversed([6, 6, 6, 4, 4, 4, 2, 2, 2, 0, 0, 0, 1, 6, 5, 5, 3, 6, 0]))
a = deque([deque([1])])
x = 0
y = 0
count = 0
aaa = 0

while arrows:
    coordi = arrows.pop() 
    x += vector[coordi][0]
    y += vector[coordi][1]
    
    if x < 0:
        a.appendleft(deque([0] * len(a[0])))
        x += 1
    if x >=len(a):
        a.append(deque([0] * len(a[0])))
    if y < 0:
        for i in range(len(a)):
            a[i].appendleft(0)
        y += 1 
    if y >= len(a[0]):
        for i in range(len(a)):
            a[i].append(0)
    
    if a[x][y] == 1:
        if aaa > 1:
            count += 1
            print(aaa)
            aaa = 0
            print(np.array(a))
    else:
        a[x][y] =1
        aaa += 1


11
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
2
[[1 1 1 1 0]
 [1 0 0 1 0]
 [1 0 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]]
3
[[1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]]


In [110]:
a

deque([deque([1, 1, 1, 1, 0]),
       deque([1, 1, 1, 1, 0]),
       deque([1, 1, 0, 1, 0]),
       deque([1, 1, 1, 1, 0]),
       deque([0, 0, 0, 1, 1])])

In [98]:
count

3

In [103]:
def solution(arrows):
    arrows = list(reversed(arrows))
    a = deque([deque([True])])
    x = 0
    y = 0
    count = 0

    while arrows:
        coordi = arrows.pop() 
        x += vector[coordi][0]
        y += vector[coordi][1]

        if x < 0:
            a.appendleft(deque([False] * len(a[0])))
            x += 1
            boolian = True
        if x >=len(a):
            a.append(deque([False] * len(a[0])))
            boolian = True
        if y < 0:
            for i in range(len(a)):
                a[i].appendleft(False)
            y += 1 
            boolian = True
        if y >= len(a[0]):
            for i in range(len(a)):
                a[i].append(False)
            boolian = True

        if a[x][y] == True:
            count += 1
        else:
            a[x][y] =True
    return a, count

solution([6, 6, 6, 4, 4, 4, 2, 2, 2, 0, 0, 0, 1, 6, 5, 5, 3, 6, 0])

(deque([deque([True, True, True, True, False]),
        deque([True, True, True, True, False]),
        deque([True, True, False, True, False]),
        deque([True, True, True, True, False]),
        deque([False, False, False, True, True])]),
 3)

In [72]:
x = 10
d = [0] * 30001

for i in range(2, x+1):
    d[i] = d[i-1] + 1
    if i % 2 ==0:
        d[i] = min(d[i], d[i//2] + 1)
    if i % 3 ==0:
        d[i] = min(d[i], d[i//3] + 1)
    #elif i % 5 == 0:
    #    d[i] = min(d[i], d[i//5] + 1)
        
print(d[x])
print(d)

3
[0, 0, 1, 1, 2, 3, 2, 3, 3, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
/ * + -

In [149]:
#print(solution(5,31168),-1)
n = 5
number = 12
a = [35000] * (n*55) 

a[n] = 1
for j in range(len(a)):
    for i in range(j):
        if int(str(i)+str(n)) < len(a):
            a[int(str(i)+str(n))] = min(a[int(str(i)+str(n))], a[i]+1)

        if 0 <= i//n < len(a):
            a[i//n] = min(a[i//n], a[i]+1)

        if 0 <= i+n < len(a):
            a[i+n] = min(a[i+n], a[i]+1)

        if 0 <= i-n < len(a):
            a[i-n] = min(a[i-n], a[i]+1)

        if 0 <= i*n < len(a):
            a[i*n] = min(a[i*n], a[i]+1)

        if 0 <= i + (n//n) < len(a):
            a[i+(n//n)] = min(a[i+(n//n)], a[i]+2)

print(a[number])

4


In [87]:
from collections import deque
n = 5
number = 31168
a = [35000] * (9*32000) 

aa = deque([n])
while aa:
    i = aa.popleft()
    if int(str(i)+str(n)) < len(a):
        a[int(str(i)+str(n))] = min(a[int(str(i)+str(n))], a[i]+1)
        aa.append(int(str(i)+str(n)))
    if 0 <= i//n < len(a):
        if a[i//n] != min(a[i//n], a[i]+1):
            a[i//n] = min(a[i//n], a[i]+1)
            aa.append(i//n)
    if 0 <= i+n < len(a):
        if a[i+n] != min(a[i+n], a[i]+1):
            a[i+n] = min(a[i+n], a[i]+1)
            aa.append(i+n)
    if 0 <= i-n < len(a):
        if a[i-n] != min(a[i-n], a[i]+1):
            a[i-n] = min(a[i-n], a[i]+1)
            aa.append(i-n)
    if 0 <= i*n < len(a):
        if a[i*n] != min(a[i*n], a[i]+1):
            a[i*n] = min(a[i*n], a[i]+1)
            aa.append(i*n)
    if 0 <= i + (n//n) < len(a):
        if a[i+(n//n)] != min(a[i+(n//n)], a[i]+2):
            a[i+(n//n)] = min(a[i+(n//n)], a[i]+2)
            aa.append(i+(n//n))
    if 0 <= i - (n//n) < len(a):
        if a[i-(n//n)] != min(a[i-(n//n)], a[i]+2):
            a[i-(n//n)] = min(a[i-(n//n)], a[i]+2)
            aa.append(i-(n//n))
print(a[number])

35000


In [134]:
aa[number]

26

In [194]:
n = 5
number = 31168
a = [35000] * int((str(n)*9))
a[n] = 1
for i in range(len(a)):
    if int(str(i)+str(n)) < len(a):
        a[int(str(i)+str(n))] = min(a[int(str(i)+str(n))], a[i]+1)

    if 0 <= i//n < len(a):
        a[i//n] = min(a[i//n], a[i]+1)

    if 0 <= i+n < len(a):
        a[i+n] = min(a[i+n], a[i]+1)
        
    if 0 <= i-n < len(a):
        a[i-n] = min(a[i-n], a[i]+1)

    if 0 <= i*n < len(a):
        a[i*n] = min(a[i*n], a[i]+1)

    if 0 <= i + (n//n) < len(a):
        a[i+(n//n)] = min(a[i+(n//n)], a[i]+2)
        
    if 0 <= i - (n//n) < len(a):
        a[i-(n//n)] = min(a[i-(n//n)], a[i]+2)

KeyboardInterrupt: 

In [193]:
555555555

'555555555'

In [191]:
a[(55//5)+5]

5

In [192]:
a[5+5+5+(5//5)]

5

In [3]:
money = [1,2,3,1]

a = [0 for i in range(len(money))]

answer = [0,0]
a[0] = money[0]
a[1] = max(money[0], money[1])
for i in range(2, len(a)-1):
    a[i] = max(a[i-1], a[i-2]+money[i])

answer[0] = a[-1]

a[0] = money[1]
a[1] = max(money[1], money[2])
for i in range(3, len(a)):
    a[i] = a[i] = max(a[i-1], a[i-2]+money[i])
answer[1] = a[-1]
max(answer)

4

In [22]:
def solution(money):
    
    a = [0 for i in range(len(money))]
    answer = []
    a[0] = money[0]
    a[1] = max(money[0], money[1])
    for i in range(2, len(a)-1):
        a[i] = max(a[i-1], a[i-2]+money[i])
    answer.append(a[-1])
    
    b = [0 for i in range(len(money))]
    b[0] = 0
    b[1] = money[1]
    for i in range(2, len(b)):
        b[i] = max(b[i-1], b[i-2]+money[i])
        print(b)
    answer.append(a[-1])
    print(a, b)
    return max(answer)

In [23]:
solution([1,2,3,1])

[0, 2, 3, 0]
[0, 2, 3, 3]
[1, 2, 4, 0] [0, 2, 3, 3]


0

In [71]:
a = [12, 121, 34, 343, 21, 2]
answer = ''
for i in range(len(a)):
    a[i] = [str(a[i])+str(a[i])[-1]*(4-len(str(a[i]))), str(a[i])]
    
a.sort(reverse=True)
for i in a:
    answer+= i[1]
a

[['3444', '34'],
 ['3433', '343'],
 ['2222', '2'],
 ['2111', '21'],
 ['1222', '12'],
 ['1211', '121']]

In [65]:
answer = ''
for i in range(len(a)):
    a[i] = [str(a[i])+str(a[i])[-1]*(4-len(str(a[i]))), str(a[i])]
    
a.sort(reverse=True)
for i in a:
    answer+= i[1]

0

In [111]:
a = [0,0,0,0,0]
answer = ''
    
a.sort(key = lambda x:(str(x)*4)[:4], reverse=True)
str(int(''.join([str(i) for i in a])))

'0'

In [114]:
import numpy as np
np.array(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 3],
       [0, 2, 5, 0, 1],
       [4, 2, 4, 4, 2],
       [3, 5, 1, 3, 1]])

In [161]:
a = [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]
moves = list(reversed([1,5,3,5,1,2,1,4]))
a = list(zip(*a))
b = []
answer = 0
while moves:
    c = moves.pop()-1
    for i in range(len(a[c])):
        a[c]= list(a[c])
        if a[c][i] != 0:
            b.append(a[c][i])
            a[c][i] = 0
            break
    print(b)
    if len(b) >= 2 and b[-1] == b[-2]:
        b = b[:-2]
        answer += 2
answer

[4]
[4, 3]
[4, 3, 1]
[4, 3, 1, 1]
[4, 3, 3]
[4, 2]
[4, 2]
[4, 2, 4]


4

In [230]:
import copy
n = 12
weak = [1, 5, 6, 10]
dist = sorted([1, 2, 3, 4])
length = len(dist)

visited = [False if i in weak else True for i in range(n)]
total_visited = [False if i in weak else True for i in range(n)]
while dist:
    print(total_visited)
    if all(total_visited):
        break
    i = dist.pop()
    for j in range(n):
        idx = j
        visited1 = copy.deepcopy(total_visited)
        for k in range(j, j+i+1):
            if idx in weak and visited1[idx] == False:
                visited1[idx] = True

            if idx == n-1:
                idx = 0
            else:
                idx += 1

        if visited.count(False) > visited1.count(False):
            visited = visited1
    total_visited = visited    
print(length-len(dist)) 

[True, False, True, True, True, False, False, True, True, True, False, True]
[True, True, True, True, True, True, False, True, True, True, False, True]
[True, True, True, True, True, True, True, True, True, True, False, True]
[True, True, True, True, True, True, True, True, True, True, True, True]
3


In [231]:
visited = [False if i in weak else True for i in range(n)]
total_visited = [False if i in weak else True for i in range(n)]
i = 
for j in range(n):
    idx = j
    visited1 = copy.deepcopy(total_visited)
    for k in range(j, j+i+1):
        print(j, idx)
        if idx in weak and visited1[idx] == False:
            visited1[idx] = True

        if idx == n-1:
            idx = 0
        else:
            idx += 1

    if visited.count(False) > visited1.count(False):
        visited = visited1
        print(visited)
        print(j)
print(visited)

0 0
0 1
0 2
0 3
0 4
[True, True, True, True, True, False, False, True, True, True, False, True]
0
1 1
1 2
1 3
1 4
1 5
[True, True, True, True, True, True, False, True, True, True, False, True]
1
2 2
2 3
2 4
2 5
2 6
3 3
3 4
3 5
3 6
3 7
4 4
4 5
4 6
4 7
4 8
5 5
5 6
5 7
5 8
5 9
6 6
6 7
6 8
6 9
6 10
7 7
7 8
7 9
7 10
7 11
8 8
8 9
8 10
8 11
8 0
9 9
9 10
9 11
9 0
9 1
10 10
10 11
10 0
10 1
10 2
11 11
11 0
11 1
11 2
11 3
[True, True, True, True, True, True, False, True, True, True, False, True]


In [ ]:
# 파이썬
from itertools import permutations
def solution(n, weak, dist):
    L = len(weak)
    cand = []
    weak_point = weak + [w+n for w in weak]  # 선형으로

    for i, start in enumerate(weak):
        for friends in permutations(dist):  # 순열 이용
            count = 1
            position = start
            # 친구 조합 배치
            for friend in friends:
                position += friend
                # 끝 포인트까지 도달 못했을 때
                if position < weak_point[i+L-1]:
                    count += 1  # 친구 더 투입
                    # 현재 위치보다 멀리 있는 취약지점 중 가장 가까운 위치로
                    position = [w for w in weak_point[i+1:i+L]
                                if w > position][0]
                else:  # 끝 포인트까지 도달
                    cand.append(count)
                    break

    return min(cand) if cand else -1

In [ ]:
for tc inrange(int(input())):
    n, m = map(int, input().split())
    array = list(map(int, input().split()))
    
    dp = []
    index = 0
    
    for i in range(n):
        dp.append(array[index:index + m])
        index += m
        
    for j in range(1, m):
        for i in range(n):           
            if i == 0: left_up =0
            else: left_up = dp[i-1][j-1]
            
            if i == n: left_down = 0 
            else: left_down = dp[i+1][j-1]
                
            