1. 문자열 압축

In [ ]:
# 내 답안 1
# 정확도 100... 하...

from itertools import combinations
def solution(a):
    answer = []
    if len(a) == 1:
        return len(a)
    for i in range(1, (len(a)//2)+1):
        start = 0
        end = i
        b = []
        while True:
            b.append(a[start:end])
            start += i
            end += i

            if end > len(a):
                b.append(a[start:end])
                break
        aa = ""
        f = 1
        for j in range(0, len(b)):
            if j < len(b)-1:
                if b[j] == b[j+1]:
                    f += 1
                else:
                    if f >= 2:
                        aa += str(f)+b[j]
                        f = 1
                    else:
                        aa += b[j]
                        f = 1
            elif j == len(b)-1:  
                if f >= 2:
                    aa += str(f)+b[j]
                    f = 1
                else:
                    aa += b[j]
                    f = 1

        answer.append(aa)
        answer.sort(key=lambda x : len(x))

    return len(answer[0])

In [ ]:
# 내 답안 2
from itertools import combinations
def solution(a):
    answer = []
    for i in range(0, len(a)):
        b = []
        for j in range(0, len(a), i+1):
            b.append(a[j:(j+i+1)])
        aa = ""
        f = 1
        for j in range(0, len(b)):
            if j < len(b)-1:
                if b[j] == b[j+1]:
                    f += 1
                else:
                    if f >= 2:
                        aa += str(f)+b[j]
                    else:
                        aa += b[j]
                    f = 1
            elif j == len(b)-1:  
                if f >= 2:
                    aa += str(f)+b[j]
                else:
                    aa += b[j]
                f = 1

        answer.append(aa)
        answer.sort(key=lambda x : len(x))
        
    return len(answer[0])

In [231]:
# 내 답안 3
import time
def solution(a):
    answer1 = []
    for i in range(0, len(a)):
        b = []
        for j in range(0, len(a), i+1):
            b.append(a[j:j+i+1])
        d = ["", "1"]
        for j in b:
            if j != d[-2]:
                d.append(j)
                d.append(str(1))
            else:
                d[-1] = str(int(d[-1]) + 1)
        d = list(filter(("1").__ne__, d))
        answer1.append("".join(d))
    answer1.sort(key = lambda x: len(x))
    return len(answer1[0])


a = [
    "aabbaccc",
    "ababcdcdababcdcd",
    "abcabcdede",
    "abcabcabcabcdededededede",
    "xababcdcdababcdcd",

    'aaaaaa',
]

for x in a:
    print(solution(x))

7
9
8
14
17
2


In [ ]:
# --- 다른 사람들 풀이 --------------------------------------------------------------------------------------------------------

In [234]:
def compress(text, tok_len):
    words = [text[i:i+tok_len] for i in range(0, len(text), tok_len)]
    print(words)
    res = []
    cur_word = words[0]
    cur_cnt = 1
    for a, b in zip(words, words[1:] + ['']):
        if a == b:
            cur_cnt += 1
        else:
            res.append([cur_word, cur_cnt])
            cur_word = b
            cur_cnt = 1
    return sum(len(word) + (len(str(cnt)) if cnt > 1 else 0) for word, cnt in res)

def solution(text):
    
    return min(compress(text, tok_len) for tok_len in list(range(1, int(len(text)/2) + 1)) + [len(text)])

a = [
    "aabbaccc",
    "ababcdcdababcdcd",
    "abcabcdede",
    "abcabcabcabcdededededede",
    "xababcdcdababcdcd",

    'aaaaaa',
]

for x in a:
    print(solution(x))

['a', 'a', 'b', 'b', 'a', 'c', 'c', 'c']
['aa', 'bb', 'ac', 'cc']
['aab', 'bac', 'cc']
['aabb', 'accc']
['aabbaccc']
7
['a', 'b', 'a', 'b', 'c', 'd', 'c', 'd', 'a', 'b', 'a', 'b', 'c', 'd', 'c', 'd']
['ab', 'ab', 'cd', 'cd', 'ab', 'ab', 'cd', 'cd']
['aba', 'bcd', 'cda', 'bab', 'cdc', 'd']
['abab', 'cdcd', 'abab', 'cdcd']
['ababc', 'dcdab', 'abcdc', 'd']
['ababcd', 'cdabab', 'cdcd']
['ababcdc', 'dababcd', 'cd']
['ababcdcd', 'ababcdcd']
['ababcdcdababcdcd']
9
['a', 'b', 'c', 'a', 'b', 'c', 'd', 'e', 'd', 'e']
['ab', 'ca', 'bc', 'de', 'de']
['abc', 'abc', 'ded', 'e']
['abca', 'bcde', 'de']
['abcab', 'cdede']
['abcabcdede']
8
['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'd', 'e', 'd', 'e', 'd', 'e', 'd', 'e', 'd', 'e', 'd', 'e']
['ab', 'ca', 'bc', 'ab', 'ca', 'bc', 'de', 'de', 'de', 'de', 'de', 'de']
['abc', 'abc', 'abc', 'abc', 'ded', 'ede', 'ded', 'ede']
['abca', 'bcab', 'cabc', 'dede', 'dede', 'dede']
['abcab', 'cabca', 'bcded', 'edede', 'dede']
['abcabc', 'abcabc', 'ded

In [289]:
a = [[100,90,98,88,65],[50,45,99,85,77],[47,88,95,80,67],[61,57,100,80,65],[24,90,94,75,65]]

def aaa(a):
    if a >= 90:
        return "A"
    elif 80<=a<90:
        return "B"
    elif 70<= a < 80:
        return "C"
    elif 50 <= a < 70:
        return "D"
    else:
        return "F"
    
b = [[k[i] for k in a] for i in range(len(a[0]))]

answer = ""
for i in range(len(b)):
    if min(b[i]) < b[i][i] < max(b[i]) or b[i].count(b[i][i]) != 1:
        answer += aaa(sum(b[i])//len(b[i]))
    else:
        del b[i][i]
        answer += aaa(sum(b[i])//len(b[i]))
answer

TypeError: range() takes no keyword arguments

In [291]:
a = [[100,90,98,88,65],[50,45,99,85,77],[47,88,95,80,67],[61,57,100,80,65],[24,90,94,75,65]]
list(zip(*a))

[(100, 50, 47, 61, 24),
 (90, 45, 88, 57, 90),
 (98, 99, 95, 100, 94),
 (88, 85, 80, 80, 75),
 (65, 77, 67, 65, 65)]

2. 괄호의 변환

In [13]:
# 문제에서 제시하는 과정을 잘 볼 필요가 있음.
# 재귀함수가 무조건 필요한 문제임
def splitt(w):
    a, b = 0, 0
    for i in range(len(w)):
        if w[i] == '(':
            a += 1
        else:
            b+=1

        if a == b:
            u, v = w[:i+1], w[i+1:]
            break

    return u, v

def dcmn(v):
    c = True
    a = []
    for i in v:
        if i =='(':
            a.append(i)
        else:
            if a:
                a.pop()
            else:
                c = False
    return c
    
def correct(b):
    b = ''.join(['(' if i == ')' else ')' for i in b])
    return b

def solution(a):
    if a == '':
        return ''
    
    answer = ''
    u, v = splitt(a)

    
    if dcmn(u): # 올바른 문자열을 충족하는지를 (를 통해서 확인함.
        answer += u + solution(v)
    else:
        answer += '('+ solution(v) + ')'
        answer += correct(u[1:-1])

    return answer

solution(')))(((')

'()(())'

3. 자물쇠와 열쇠

In [73]:
import copy
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]
#도는거
#오른쪽으로 가는거 

#1) 오른쪽으로 도는거 모두 실행 -> 비교
#2) 회전 한번, 오른쪽으로 도는거 모두 실행 -> 비교

# 오른쪽으로 한칸 이동하는 함수
# 단, key의 경우에만 적용가능 함
def r_move(a):
    b = copy.deepcopy(a)
    for i in range(len(a)):
        for j in range(len(a[0])):
            if j != len(a[0])-1:
                b[i][j+1] = a[i][j]
            else:
                b[i][0] = 0
    return b

# 한칸 회전하는 함수(단, 오른쪽으로만 회전함)
def rotation(a):
    if len(a) % 2 == 0:
        c = (len(a)//2)+1
    else:
        c = len(a)//2

    for i in range(c):
        # 첫 행
        for j in range(i, (len(a[i])-i)):
            if j == i:
                tem = a[i][j]
            else:
                tem_1 = a[i][j]
                a[i][j] = tem
                tem = tem_1

        # 마지막 열일 때, 밑으로
        for j in range(i+1, len(a)-i):
            tem_1 = a[j][len(a)-i-1]
            a[j][len(a)-i-1] = tem
            tem = tem_1

        # 마지막 행일 때, 왼쪽으로
        for j in range(len(a)-i-2, i-1, -1):
            tem_1 = a[len(a)-i-1][j]
            a[len(a)-i-1][j] = tem
            tem = tem_1

        # 첫 행일 때. 위로
        for j in range(len(a)-i-2, i-1, -1):
            tem_1 = a[j][i]
            a[j][i] = tem
            tem = tem_1
        return a
    
# 1) 먼저 키를 오른쪽으로 한칸씩 돌려가면서 비교한다.
#    단, key가 lock보다 작을 수 있으므로 
for i in range(len(key[0])):
    key = rotation(key)
    print(np.array(key))    

[[1 0 0]
 [0 0 0]
 [1 1 0]]
[[0 1 0]
 [1 0 0]
 [1 0 0]]
[[1 0 1]
 [1 0 0]
 [0 0 0]]


In [125]:
import copy
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]
#도는거
#오른쪽으로 가는거 

#1) 오른쪽으로 도는거 모두 실행 -> 비교
#2) 왼쪽으로도 가야함...
#2) 회전 한번, 오른쪽으로 도는거 모두 실행 -> 비교

# 오른쪽으로 한칸 이동하는 함수
# 단, key의 경우에만 적용가능 함
def r_move(a):
    b = copy.deepcopy(a)
    for i in range(len(a)):
        for j in range(len(a[0])):
            if j != len(a[0])-1:
                b[i][j+1] = a[i][j]
            else:
                b[i][0] = 0
    return b

# 한칸 회전하는 함수(단, 오른쪽으로만 회전함)
def rotation(a):
    if len(a) % 2 == 0:
        c = (len(a)//2)+1
    else:
        c = len(a)//2

    for i in range(c):
        # 첫 행
        for j in range(i, (len(a[i])-i)):
            if j == i:
                tem = a[i][j]
            else:
                tem_1 = a[i][j]
                a[i][j] = tem
                tem = tem_1

        # 마지막 열일 때, 밑으로
        for j in range(i+1, len(a)-i):
            tem_1 = a[j][len(a)-i-1]
            a[j][len(a)-i-1] = tem
            tem = tem_1

        # 마지막 행일 때, 왼쪽으로
        for j in range(len(a)-i-2, i-1, -1):
            tem_1 = a[len(a)-i-1][j]
            a[len(a)-i-1][j] = tem
            tem = tem_1

        # 첫 행일 때. 위로
        for j in range(len(a)-i-2, i-1, -1):
            tem_1 = a[j][i]
            a[j][i] = tem
            tem = tem_1
        return a

# 먼저 회전을 해야 함. 
key_copy = copy.deepcopy(key)
while True:
    key_copy = rotation(key_copy)
    print(key_copy)
    if key_copy == key:
        break
        
    move_key = copy.deepcopy(key_copy)
    # 오른쪽으로 돌릴 것
    for _ in range(len(a)):
        
        

[[1, 0, 0], [0, 0, 0], [1, 1, 0]]
[[0, 1, 0], [1, 0, 0], [1, 0, 0]]
[[1, 0, 1], [1, 0, 0], [0, 0, 0]]
[[1, 1, 0], [0, 0, 1], [0, 0, 0]]
[[0, 1, 1], [0, 0, 0], [0, 0, 1]]
[[0, 0, 1], [0, 0, 1], [0, 1, 0]]
[[0, 0, 0], [0, 0, 1], [1, 0, 1]]
[[0, 0, 0], [1, 0, 0], [0, 1, 1]]


In [132]:
import copy
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]


# 오른쪽으로 한칸 이동하는 함수
# 단, key의 경우에만 적용가능 함
def r_move(a):
    b = copy.deepcopy(a)
    for i in range(len(a)):
        for j in range(len(a[0])):
            if j != len(a[0])-1:
                b[i][j+1] = a[i][j]
            else:
                b[i][0] = 1
    return b

# 한칸 회전하는 함수(단, 오른쪽으로만 회전함)
def rotation(a):
    if len(a) % 2 == 0:
        c = (len(a)//2)+1
    else:
        c = len(a)//2

    for i in range(c):
        # 첫 행
        for j in range(i, (len(a[i])-i)):
            if j == i:
                tem = a[i][j]
            else:
                tem_1 = a[i][j]
                a[i][j] = tem
                tem = tem_1

        # 마지막 열일 때, 밑으로
        for j in range(i+1, len(a)-i):
            tem_1 = a[j][len(a)-i-1]
            a[j][len(a)-i-1] = tem
            tem = tem_1

        # 마지막 행일 때, 왼쪽으로
        for j in range(len(a)-i-2, i-1, -1):
            tem_1 = a[len(a)-i-1][j]
            a[len(a)-i-1][j] = tem
            tem = tem_1

        # 첫 행일 때. 위로
        for j in range(len(a)-i-2, i-1, -1):
            tem_1 = a[j][i]
            a[j][i] = tem
            tem = tem_1
        return a

    
for i in range(len(key)):
    for j in range(len(key[0])):
        if key[i][j] == 0:
            key[i][j] = 1
        else:
            key[i][j] = 0

        

[[1, 1, 1], [1, 1, 0], [1, 1, 1]]

In [136]:
def rotate(arr):
    return list(zip(*arr[::-1]))
print(np.array([[0, 0, 0], [1, 0, 0], [0, 1, 1]]))
np.array(rotate([[0, 0, 0], [1, 0, 0], [0, 1, 1]]))

[[0 0 0]
 [1 0 0]
 [0 1 1]]


array([[0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

4. 기둥과 보 설치

In [13]:
# 0 : 기둥, 1: 보
# 0: 삭제, 1: 설치
build_frame = [[1,0,0,1],[1,1,1,1],[2,1,0,1],[2,2,1,1],[5,0,0,1],[5,1,0,1],[4,2,1,1],[3,2,1,1]]
result = [[1,0,0],[1,1,1],[2,1,0],[2,2,1],[3,2,1],[4,2,1],[5,0,0],[5,1,0]]

In [14]:
from collections import deque

build_frame = [[0,0,0,1],[2,0,0,1],[4,0,0,1],
               [0,1,1,1],[1,1,1,1],[2,1,1,1],
               [3,1,1,1],[2,0,0,0],[1,1,1,0],[2,2,0,1]]

build_frame = deque(build_frame)
build = {}
while build_frame:
    c = build_frame.popleft()
    
    build[(c[0], c[1])] = build.get((c[0], c[1]), [c[2]])
    
build

[1, 0, 0, 1]
[1, 1, 1, 1]
[2, 1, 0, 1]
[2, 2, 1, 1]
[5, 0, 0, 1]
[5, 1, 0, 1]
[4, 2, 1, 1]
[3, 2, 1, 1]


{(1, 0): 0,
 (1, 1): 1,
 (2, 1): 0,
 (2, 2): 1,
 (5, 0): 0,
 (5, 1): 0,
 (4, 2): 1,
 (3, 2): 1}

In [65]:
# 보를 어떻게 표현할 것인가. - 매트릭스의 선을 어떻게 표현해야 하는가.

from collections import deque
import numpy as np

build_frame = [[0,0,0,1],[2,0,0,1],[4,0,0,1],
               [0,1,1,1],[1,1,1,1],[2,1,1,1],
               [3,1,1,1],[2,0,0,0],[1,1,1,0],[2,2,0,1]]

build_frame_sort = sorted(build_frame)
# 기둥이 세워졌는지 판단할 매트릭스 생성
# 기둥이 세워지면 True
a = [[0 for j in range(10)] for i in range(10)]

# 보가 세워졌는지 판단할 매트릭스
build_frame_sort = sorted(build_frame, key = lambda x:x[1])
b = [[0 for j in range(10)] for i in range(10)]

pillar = []
beam = []
for i in build_frame:
    x, y = i[1], i[0] # x 좌표는 열의 좌표, y 좌표는 행의 좌표
    
    # 세울 때.
    # 기둥일 때.
    if i[2] == 0 and i[3] == 1:
        if a[x-1][y] == 1 or x == 0:
            a[x][y] = 1
            pillar.append(i[:3])
            
    if i[2] == 1 and i[3] == 1:
        if a[x-1][y] == 1:
            b[x][y] = 1
            beam.append(i[:3])
        elif (b[x][y-1] == 1 and b[x][y+1] == 1):
            b[x][y] = 1
            beam.append(i[:3])
        

print(x, y)
print(a)
b

2 2
[[1, 0, 1, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [ ]:
#--- 다른 사람 풀이 --------------------------------------------------------------

In [ ]:
def impossible(result):
    COL, ROW = 0, 1
    for x, y, a in result:
        if a == COL: # 기둥일 때
            if y != 0 and (x, y-1, COL) not in result and \(x-1, y, ROW) not in result and (x, y, ROW) not in result:
                return True
        else: # 보일 때
            if (x, y-1, COL) not in result and (x+1, y-1, COL) not in result and \
        not ((x-1, y, ROW) in result and (x+1, y, ROW) in result):
                return True
    return False

def solution(n, build_frame):
    result = set()
    
    for x, y, a, build in build_frame:
        item = (x, y, a)
        if build: # 추가일 때
            result.add(item)
            if impossible(result):
                result.remove(item)
        elif item in result: # 삭제할 때
            result.remove(item)
            if impossible(result):
                result.add(item)
    answer = map(list, result)
    
    return sorted(answer, key = lambda x : (x[0], x[1], x[2]))