1. 문자열 압축

In [ ]:
# 내 답안 1
from itertools import combinations
def solution(a):
    answer = []
    if len(a) == 1:
        return len(a)
    for i in range(1, (len(a)//2)+1):
        start = 0
        end = i
        b = []
        while True:
            b.append(a[start:end])
            start += i
            end += i

            if end > len(a):
                b.append(a[start:end])
                break
        aa = ""
        f = 1
        for j in range(0, len(b)):
            if j < len(b)-1:
                if b[j] == b[j+1]:
                    f += 1
                else:
                    if f >= 2:
                        aa += str(f)+b[j]
                        f = 1
                    else:
                        aa += b[j]
                        f = 1
            elif j == len(b)-1:  
                if f >= 2:
                    aa += str(f)+b[j]
                    f = 1
                else:
                    aa += b[j]
                    f = 1

        answer.append(aa)
        answer.sort(key=lambda x : len(x))

    return len(answer[0])

In [231]:
# 내 답안 2
import time
def solution(a):
    answer1 = []
    for i in range(0, len(a)):
        b = []
        for j in range(0, len(a), i+1):
            b.append(a[j:j+i+1])
        d = ["", "1"]
        for j in b:
            if j != d[-2]:
                d.append(j)
                d.append(str(1))
            else:
                d[-1] = str(int(d[-1]) + 1)
        d = list(filter(("1").__ne__, d))
        answer1.append("".join(d))
    answer1.sort(key = lambda x: len(x))
    return len(answer1[0])


a = ["aabbaccc",
    "ababcdcdababcdcd",
    "abcabcdede",
    "abcabcabcabcdededededede",
    "xababcdcdababcdcd",
    'aaaaaa',]

for x in a:
    print(solution(x))

7
9
8
14
17
2


In [ ]:
# 나중에 다시 풀어본 내 답안 3
def solution(a):
    answer = len(a)
    for i in range(1, len(a)+1):
        count = ['1', a[0:i]]
        for j in range(i, len(a), i):
            if a[j:j+i] == count[-1]:
                count[-2] = str(int(count[-2])+1)
            else: 
                count.extend(['1', a[j:j+i]])
        count = [k if k != '1' else '' for k in count]
        if answer > len(''.join(count)): answer = len(''.join(count))
    return answer

# 더 나중에 다시 풀어본 답 4
def solution(s):
    if len(s) ==1: return 1
    answer= []
    for i in range(1, len(s)):
        a = []
        for j in range(0,len(s), i):
            if a != [] and a[-1][1] == s[j:j+i]:
                a[-1][0] += 1
            else:
                a.append([1, s[j:j+i]])
        answer.append(len(''.join(list(map(lambda x: str(x[0])+x[1] if x[0] != 1 else x[1], a)))))
    return min(answer)

In [ ]:
# --- 다른 사람들 풀이 --------------------------------------------------------------------------------------------------------

In [234]:
def compress(text, tok_len):
    words = [text[i:i+tok_len] for i in range(0, len(text), tok_len)]
    print(words)
    res = []
    cur_word = words[0]
    cur_cnt = 1
    for a, b in zip(words, words[1:] + ['']):
        if a == b:
            cur_cnt += 1
        else:
            res.append([cur_word, cur_cnt])
            cur_word = b
            cur_cnt = 1
    return sum(len(word) + (len(str(cnt)) if cnt > 1 else 0) for word, cnt in res)

def solution(text):
    
    return min(compress(text, tok_len) for tok_len in list(range(1, int(len(text)/2) + 1)) + [len(text)])

a = [
    "aabbaccc",
    "ababcdcdababcdcd",
    "abcabcdede",
    "abcabcabcabcdededededede",
    "xababcdcdababcdcd",

    'aaaaaa',
]

for x in a:
    print(solution(x))

['a', 'a', 'b', 'b', 'a', 'c', 'c', 'c']
['aa', 'bb', 'ac', 'cc']
['aab', 'bac', 'cc']
['aabb', 'accc']
['aabbaccc']
7
['a', 'b', 'a', 'b', 'c', 'd', 'c', 'd', 'a', 'b', 'a', 'b', 'c', 'd', 'c', 'd']
['ab', 'ab', 'cd', 'cd', 'ab', 'ab', 'cd', 'cd']
['aba', 'bcd', 'cda', 'bab', 'cdc', 'd']
['abab', 'cdcd', 'abab', 'cdcd']
['ababc', 'dcdab', 'abcdc', 'd']
['ababcd', 'cdabab', 'cdcd']
['ababcdc', 'dababcd', 'cd']
['ababcdcd', 'ababcdcd']
['ababcdcdababcdcd']
9
['a', 'b', 'c', 'a', 'b', 'c', 'd', 'e', 'd', 'e']
['ab', 'ca', 'bc', 'de', 'de']
['abc', 'abc', 'ded', 'e']
['abca', 'bcde', 'de']
['abcab', 'cdede']
['abcabcdede']
8
['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'd', 'e', 'd', 'e', 'd', 'e', 'd', 'e', 'd', 'e', 'd', 'e']
['ab', 'ca', 'bc', 'ab', 'ca', 'bc', 'de', 'de', 'de', 'de', 'de', 'de']
['abc', 'abc', 'abc', 'abc', 'ded', 'ede', 'ded', 'ede']
['abca', 'bcab', 'cabc', 'dede', 'dede', 'dede']
['abcab', 'cabca', 'bcded', 'edede', 'dede']
['abcabc', 'abcabc', 'ded

In [289]:
a = [[100,90,98,88,65],[50,45,99,85,77],[47,88,95,80,67],[61,57,100,80,65],[24,90,94,75,65]]

def aaa(a):
    if a >= 90:
        return "A"
    elif 80<=a<90:
        return "B"
    elif 70<= a < 80:
        return "C"
    elif 50 <= a < 70:
        return "D"
    else:
        return "F"
    
b = [[k[i] for k in a] for i in range(len(a[0]))]

answer = ""
for i in range(len(b)):
    if min(b[i]) < b[i][i] < max(b[i]) or b[i].count(b[i][i]) != 1:
        answer += aaa(sum(b[i])//len(b[i]))
    else:
        del b[i][i]
        answer += aaa(sum(b[i])//len(b[i]))
answer

TypeError: range() takes no keyword arguments

In [291]:
a = [[100,90,98,88,65],[50,45,99,85,77],[47,88,95,80,67],[61,57,100,80,65],[24,90,94,75,65]]
list(zip(*a))

[(100, 50, 47, 61, 24),
 (90, 45, 88, 57, 90),
 (98, 99, 95, 100, 94),
 (88, 85, 80, 80, 75),
 (65, 77, 67, 65, 65)]

2. 괄호의 변환

In [13]:
# 문제에서 제시하는 과정을 잘 볼 필요가 있음.
# 재귀함수가 무조건 필요한 문제임
def splitt(w):
    a, b = 0, 0
    for i in range(len(w)):
        if w[i] == '(':
            a += 1
        else:
            b+=1

        if a == b:
            u, v = w[:i+1], w[i+1:]
            break

    return u, v

def dcmn(v):
    c = True
    a = []
    for i in v:
        if i =='(':
            a.append(i)
        else:
            if a:
                a.pop()
            else:
                c = False
    return c
    
def correct(b):
    b = ''.join(['(' if i == ')' else ')' for i in b])
    return b

def solution(a):
    if a == '':
        return ''
    
    answer = ''
    u, v = splitt(a)

    
    if dcmn(u): # 올바른 문자열을 충족하는지를 (를 통해서 확인함.
        answer += u + solution(v)
    else:
        answer += '('+ solution(v) + ')'
        answer += correct(u[1:-1])

    return answer

solution(')))(((')

'()(())'

In [ ]:
# 다른 사람이 푼 답
def solution(p):
    if p=='': return p
    r=True; c=0
    for i in range(len(p)):
        if p[i]=='(': c-=1
        else: c+=1
        if c>0: r=False
        if c==0:
            if r:
                return p[:i+1]+solution(p[i+1:])
            else:
                return '('+solution(p[i+1:])+')'+''.join(list(map(lambda x:'(' if x==')' else ')',p[1:i]) ))

3. 자물쇠와 열쇠

In [ ]:
# 나중에 시간 지나고 다시 풀어본 것
import copy

def check(matrix, x, y):
    for i in range(x):
        for j in range(x):
            if matrix[i+y-1][j+y-1] != 1:
                return False
    return True

def solution(key, lock):
    # 비교할 큰 매트릭스 만들기
    # lock의 각 행과 옆의 앞, 뒤쪽에 추가될 것은 key의 길이에서 1을 뺀 만큼.
    a = [[0 for j in range(((len(key)-1)*2) +len(lock))] for i in range(((len(key)-1)*2)+len(lock))]
    
    # 큰 매트릭스의 정앙의 작은 매트릭스를 lock로 만들기
    for i in range(len(lock)):
        for j in range(len(lock)):
            a[i+len(key)-1][j+len(key)-1] = lock[i][j] 

    
    for i in range(4):
        # n과 m은 작은 매트릭스의 왼쪽 꼭짓점 위
        # 즉, n과 m으로부터 +len(key) 까지 for문을 돌려야 함. 
        # 그게 i와 j for문임.
        for n in range(len(a)-(len(key)-1)):
            for m in range(len(a)-(len(key)-1)):
                lock_copy = copy.deepcopy(a)
                for x in range(len(key)):
                    for y in range(len(key)):
                        lock_copy[n+x][m+y] += key[x][y]
                if check(lock_copy, len(lock), len(key)):
                    return True
                
        key = list(map(lambda x: list(x), list(zip(*key[::-1]))))
    return False

In [73]:
# 다른 사람 답안 
def attach(x, y, M, key, board):
    for i in range(M):
        for j in range(M):
            board[x+i][y+j] += key[i][j]

def detach(x, y, M, key, board):
    for i in range(M):
        for j in range(M):
            board[x+i][y+j] -= key[i][j]

def rotate90(arr):
    return list(zip(*arr[::-1]))

def check(board, M, N):
    for i in range(N):
        for j in range(N):
            if board[M+i][M+j] != 1:
                return False;
    return True

def solution(key, lock):
    M, N = len(key), len(lock)

    board = [[0] * (M*2 + N) for _ in range(M*2 + N)]
    # 자물쇠 중앙 배치
    for i in range(N):
        for j in range(N):
            board[M+i][M+j] = lock[i][j]

    rotated_key = key
    # 모든 방향 (4번 루프)
    for _ in range(4):
        rotated_key = rotate90(rotated_key)
        for x in range(1, M+N):
            for y in range(1, M+N):
                # 열쇠 넣어보기
                attach(x, y, M, rotated_key, board)
                # lock 가능 check
                if(check(board, M, N)):
                    return True
                # 열쇠 빼기
                detach(x, y, M, rotated_key, board)
                
    return False

[[1 0 0]
 [0 0 0]
 [1 1 0]]
[[0 1 0]
 [1 0 0]
 [1 0 0]]
[[1 0 1]
 [1 0 0]
 [0 0 0]]


4. 기둥과 보 설치

In [13]:
# 0 : 기둥, 1: 보
# 0: 삭제, 1: 설치
build_frame = [[1,0,0,1],[1,1,1,1],[2,1,0,1],[2,2,1,1],[5,0,0,1],[5,1,0,1],[4,2,1,1],[3,2,1,1]]
result = [[1,0,0],[1,1,1],[2,1,0],[2,2,1],[3,2,1],[4,2,1],[5,0,0],[5,1,0]]

In [14]:
from collections import deque

build_frame = [[0,0,0,1],[2,0,0,1],[4,0,0,1],
               [0,1,1,1],[1,1,1,1],[2,1,1,1],
               [3,1,1,1],[2,0,0,0],[1,1,1,0],[2,2,0,1]]

build_frame = deque(build_frame)
build = {}
while build_frame:
    c = build_frame.popleft()
    
    build[(c[0], c[1])] = build.get((c[0], c[1]), [c[2]])
    
build

[1, 0, 0, 1]
[1, 1, 1, 1]
[2, 1, 0, 1]
[2, 2, 1, 1]
[5, 0, 0, 1]
[5, 1, 0, 1]
[4, 2, 1, 1]
[3, 2, 1, 1]


{(1, 0): 0,
 (1, 1): 1,
 (2, 1): 0,
 (2, 2): 1,
 (5, 0): 0,
 (5, 1): 0,
 (4, 2): 1,
 (3, 2): 1}

In [65]:
# 보를 어떻게 표현할 것인가. - 매트릭스의 선을 어떻게 표현해야 하는가.

from collections import deque
import numpy as np

build_frame = [[0,0,0,1],[2,0,0,1],[4,0,0,1],
               [0,1,1,1],[1,1,1,1],[2,1,1,1],
               [3,1,1,1],[2,0,0,0],[1,1,1,0],[2,2,0,1]]

build_frame_sort = sorted(build_frame)
# 기둥이 세워졌는지 판단할 매트릭스 생성
# 기둥이 세워지면 True
a = [[0 for j in range(10)] for i in range(10)]

# 보가 세워졌는지 판단할 매트릭스
build_frame_sort = sorted(build_frame, key = lambda x:x[1])
b = [[0 for j in range(10)] for i in range(10)]

pillar = []
beam = []
for i in build_frame:
    x, y = i[1], i[0] # x 좌표는 열의 좌표, y 좌표는 행의 좌표
    
    # 세울 때.
    # 기둥일 때.
    if i[2] == 0 and i[3] == 1:
        if a[x-1][y] == 1 or x == 0:
            a[x][y] = 1
            pillar.append(i[:3])
            
    if i[2] == 1 and i[3] == 1:
        if a[x-1][y] == 1:
            b[x][y] = 1
            beam.append(i[:3])
        elif (b[x][y-1] == 1 and b[x][y+1] == 1):
            b[x][y] = 1
            beam.append(i[:3])
        

print(x, y)
print(a)
b

2 2
[[1, 0, 1, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [ ]:
# 다른 사람 풀이 1
def impossible(result):
    COL, ROW = 0, 1
    for x, y, a in result:
        if a == COL: # 기둥일 때
            # y == 0 이거나 밑에 기둥이 없거나, 왼쪽 옆에 보가 없거나, 현재 위치에 보가 없을 때
            if y != 0 and (x, y-1, COL) not in result and \(x-1, y, ROW) not in result and (x, y, ROW) not in result:
                return True
        else: # 보일 때
            if (x, y-1, COL) not in result and (x+1, y-1, COL) not in result and \
        not ((x-1, y, ROW) in result and (x+1, y, ROW) in result):
                return True
    return False

def solution(n, build_frame):
    result = set()
    
    for x, y, a, build in build_frame:
        item = (x, y, a)
        if build: # 추가일 때
            result.add(item)
            if impossible(result):
                result.remove(item)
        elif item in result: # 삭제할 때
            result.remove(item)
            if impossible(result):
                result.add(item)
    answer = map(list, result)
    
    return sorted(answer, key = lambda x : (x[0], x[1], x[2]))

In [ ]:
# 다른 사람 풀이 2
def isValid(answer):
    for x,y,a in answer:
        if a==0:
            if (x,y-1,0) in answer or (x-1,y,1) in answer or (x,y,1) in answer or y==0:
                continue
            else:
                return False
        if a==1:
            if (x,y-1,0) in answer or (x+1,y-1,0) in answer or ((x-1,y,1) in answer and (x+1,y,1) in answer):
                continue
            else:
                return False
    return True

def solution(n, build_frame):
    answer = set()
    for x,y,a,b in build_frame:
        if b==0:
            answer.remove((x,y,a))
            if not isValid(answer):
                answer.add((x,y,a))
        else:
            answer.add((x,y,a))
            if not isValid(answer):
                answer.remove((x,y,a))

    answer = [list(i) for i in answer]
    answer.sort(key=lambda x:(x[0],x[1],x[2]))
    return answer

In [17]:
class a:
    x : int
b = a
b.x

AttributeError: type object 'a' has no attribute 'x'